### Register a new user (you need to implement saving logic)
 POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "ann",
  "password": "password123",
  "email": "random@gmail.com"
}

###

### Try login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "ann",
  "password": "password123"
}

###
GET http://localhost:8080/api/test/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWtlIiwiaWF0IjoxNzUzODQ3NzIzLCJleHAiOjE3NTM4ODM3MjN9.mfc_7rMYv3sS6fz3hn56DLu4BJXOwaBNU1ROMob3ADE
